version: "3"

services:
  node:
    image: node:16
    container_name: api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      DB_HOST: db
      DB_NAME: task_list_ebytr
      DB_USER: root
      DB_PASSWORD: password
      SERVER_PORT: 3001
  db:
    container_name: ebytr_db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    name: ebytr_net